name: SSH Sync
run-name: ${{ github.actor }} is syncing webserver
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/cm2.fi
            git pull
